--- 
- hosts: localhost
  vars: 
    applications: 
      - 1password
      - 1password-cli
      - adobe-acrobat-reader
      - autoconf
      - autojump
      - awscli
      - bash
      - battle-net
      - beyond-compare
      - blue-sherpa
      - cowsay
      - coreutils
      - docker
      - homebrew-cask-drivers/Casks/elgato-control-center
      - homebrew-cask-drivers/Casks/elgato-stream-deck
      #- evernote - found in macstore
      - findutils
      - g-desktop-suite
      - git
      - go
      - google-chat
      - google-chrome
      - google-cloud-sdk
      - google-drive
      - gpg
      - hub
      - hp-connectivity-kit
      - hp-easy-start
      - hp-eprint
      - hp-prime
      - iterm2
      - keybase # i dont think this works
      - kindle
      - logitech-presentation                                             
      - homebrew/cask-drivers/logitech-firmwareupdatetool                 
      - homebrew/cask-drivers/logitech-myharmony
      - homebrew/cask-drivers/logitech-camera-settings                    
      - homebrew/cask-drivers/logitech-g-hub                              
      - homebrew/cask-drivers/logitech-options
      - homebrew/cask-drivers/logitech-control-center                     
      - homebrew/cask-drivers/logitech-gaming-software                    
      - homebrew/cask-drivers/logitech-unifying
      - macdive
      - mas
      #- microsoft-auto-update
      - microsoft-edge
      #- microsoft-excel
      - microsoft-lync
      - microsoft-office
      #- microsoft-outlook
      #- microsoft-power-point
      #- microsoft-remote-desktop
      - microsoft-teams
      #- microsoft-word
      - mtr
      - node
      - postgresql
      - postman
      - python
      - rbenv
      - readline
      - redis
      - rename
      - rsync
      - ruby
      - ruby-build
      - skype
      - skype-for-business
      - skypewebplugin
      #- slack dont think this works, found in mac store
      - signal
      - sqlite
      - steam
      - sourcetree
      - sublime-merge
      - sublime-text
      - the_silver_searcher
      - tmux
      - vim
      - visual-studio-code
      - webex-meetings
      - webex
      - wget
      - wireshark
      - youtube-downloader
      - youtube-to-mp3
      - zsh
      - zoom
    macstore:
      - 803453959 #slack
      - 1147396723 #whatsapp
      - 1480068668 #messenger
      - 747648890 #discord
      - 747648890 #telegram
      - 406056744 #evernote
      - 462054704  #Microsoft Word                                                                         (16.47)
      - 985367838  #Microsoft Outlook                                                                      (16.47)
      - 784801555  #Microsoft OneNote                                                                      (16.47)
      - 462058435  #Microsoft Excel                                                                        (16.47.1)
      - 462062816  #Microsoft PowerPoint                                                                   (16.47)
      - 1295203466  #Microsoft Remote Desktop                                                               (10.5.2)
      - 1274495053  #Microsoft To Do                                                                        (2.40)
      - 496465537  #Whiteboard Easy and Smart                                                              (15.5)
      - 823766827  #3OneDrive 

    dotfile_repo_username: janemiceli
    home: "{{ lookup('env','HOME') }}"
  tasks: 
    - 
      name: "Check Homebrew is installed"
      register: brew_installed
      stat: path=/usr/local/bin/brew
    - 
      name: "Install Homebrew"
      shell: "ruby -e \"$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)\""
      when: "brew_installed.stat.exists == false"
    - 
      name: Check for installed apps with brew
      shell: "brew list | grep {{ item }}"
      register: installed_applications
      with_items: "{{ applications }}"
      ignore_errors: true
    -
      name: "Install Apps with mas"
      shell: "mas install {{ item }}"
    #  when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"
      with_items: "{{ macstore}}"
    -  
      name: "Install Apps with brew"
      shell: "brew install {{ item }}"
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"
      with_items: "{{ applications}}"
